### ISSUE TITLE
Can't run app

### ISSUE THREAD

**Issue by math625f** [freeCodeCamp/league-for-good#1]
I'm having problems running the application, getting the following error:
`SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode`

I haven't used node much, I've tried googling the issue but so far I haven't found anything useful.. Will I have to edit every .js file, to change variables from let and so on to var?

**Comment by makkoli** [comment]
No, wepback is supposed to transpile all ES6 functionality to ES5. Once you have the project, run "npm install" in the root directory where package.json is and then "npm run dev". This will host a node.js server at localhost:4000 that you can point your browser to. Keep in mind that this is still a work in progress so we haven't built a production configuration with webpack yet. Let me know if this doesn't work.

**Comment by math625f** [comment]
@makkoli This is what I did, so I probably just did something wrong along the way..
I'll clone a fresh repo and try again!

**Comment by ahstein3521** [comment]
You might need to update to a newer version of node.

**Comment by math625f** [comment]
Working now, thanks! Now I just need to figure out how to make the login form work ^^

I'll mark this issue as closed right away!
