### ISSUE TITLE
Switch to FCC's Eslint Config

### ISSUE THREAD

**Issue by lanesawyer** [freeCodeCamp/league-for-good#10]
I think it might be valuable to switch over to using FCC's eslint config to help standardize the styling guidelines used across the many FCC projects.

I've already ran it using the FCC config and there were over 1000 errors. I'm perfectly happy to go address all of them, but I wanted to check to see if that's something that's even desired for this project.

**Comment by CodeNonprofit** [comment]
Yes, if you'd like to do this we'd be happy to have your help. Thanks Lane.
