### ISSUE TITLE
Button and Dashboard is no longer working

### ISSUE THREAD

**Issue by paulywill** [freeCodeCamp/league-for-good#108]
Need some confirmation... but I have tried to generate a new clone from the repo and the dashboard does not appear to be working for any of the buttons.

Is anyone else having this issue with a fresh copy?

**Comment by paulywill** [comment]
@makkoli : is there any reason some of the buttons on the dashboard would stop working?

**Comment by paulywill** [comment]
![image](https://user-images.githubusercontent.com/602422/45129004-15bc6100-b14f-11e8-9a01-ca286447f907.png)

**Comment by paulywill** [comment]
I'm trying to test if the issue is because of the depreciation of [material-ui](https://www.npmjs.com/package/material-ui)  and reference [@material-ui/core](https://www.npmjs.com/package/@material-ui/core) instead in [CreateLeagueSelector.jsx](https://github.com/freeCodeCamp/league-for-good/blob/master/client/src/components/create_league/CreateLeagueSelector.jsx)

ie.

```
import React from 'react';
import PropTypes from 'prop-types';
import {
	Card,
	CardActions,
	CardTitle
} from '@material-ui/core/Card';
import CreateLeagueButton from './CreateLeagueButton.jsx';

import { sports } from '../sports.js';
import { cssCreateLeague } from '../styles';


// Creates a list of different buttons for selecting
// a sport type for the new league
// Once a sport type is selected, the proper form will be rendered
const CreateLeagueSelector = ({onSelect, selectedSport})=> (
	<Card style={cssCreateLeague.card.style}>
		<CardTitle
			subtitle='Choose a sport'
			subtitleColor={cssCreateLeague.card.title.subtitleColor}
			title='Create a New League'
			titleColor={cssCreateLeague.card.title.titleColor}
		/>
		<CardActions>
			{sports.map((sport, i) => {
				return (
					<CreateLeagueButton
						active={selectedSport === sport.name}
						icon={sport.icon}
						key={i}
						label={sport.name}
						onClick={onSelect}
					/>
				);
			})
		}
		</CardActions>
	</Card>
);

CreateLeagueSelector.propTypes = {
	onSelect: PropTypes.func,
	selectedSport: PropTypes.string
};

export default CreateLeagueSelector;

```

However the Eslint in my Atom is picking up the following:

`Error	ESLint	Unable to resolve path to module '@material-ui/core/Card'. (import/no-unresolved)	7:8`

Even though I added and updated the package.json @material-ui is still not being added to the webpack.

**Comment by paulywill** [comment]
After studying the history of [TravisCI builds](https://travis-ci.org/freeCodeCamp/league-for-good/builds) I git checkout  [74a6fb9](https://github.com/freeCodeCamp/league-for-good/commit/74a6fb98d8c6d7edf96861200901ec080ac2bb5e) which was the last successful build.

The dashboard appears to functional at this point.

Some of the recent commits will have have to be checked as to which causing the issue.

**Comment by paulywill** [comment]
@ahstein3521 : what were the features you were implementing in  [b1982a2](https://github.com/freeCodeCamp/league-for-good/commit/b1982a22b9cc3f3e1d4b50cec86dab3966a570b2)?

**Comment by paulywill** [comment]
Commit for master: [8916011](https://github.com/freeCodeCamp/league-for-good/commit/8916011c36a0213ae49e76d8771afc28c754a07a) appears to compile correctly as well.

**Comment by lieberscott** [comment]
I figured it out. The onTouchTap event has been deprecated from material-ui and needed to be replaced with onClick in the CreateLeagueButton.jsx file
it should work now, I submitted a pull request [https://github.com/freeCodeCamp/league-for-good/pull/109]

**Comment by paulywill** [comment]
@lieberscott Can you check the other view/panels?

ie the Games list icon is not working, but the Teams roaster list icon is for mine.

**Comment by lieberscott** [comment]
@paulywill Ahh, yes, same here. It seems there are onTouchTap functions throughout the code. I'm making my way through to replace them all with onClick. Games icon you referenced is here ... 

client > src > components > dashboard > seasons > seasons_list > seasonLink.jsx

changing onTouchTap to onClick should work there. Let me know. Meanwhile I'll make a new PR when I think I've replaced all the onTouchTap's

**Comment by lieberscott** [comment]
I just updated the PR, I think I got them all working

**Comment by paulywill** [comment]
@lieberscott, nice!
There may be a few more. 

The delete button under games doesn't appear to work.
![image](https://user-images.githubusercontent.com/602422/45270402-1d3f7b00-b46b-11e8-9d97-4e79911b8499.png)

Nor the back button when editing a game.

![image](https://user-images.githubusercontent.com/602422/45270426-5546be00-b46b-11e8-919e-0e354fafff15.png)


This is where some more TDD and tests would catch these ones.
