### ISSUE TITLE
Fix/Remove the update column under team roster

### ISSUE THREAD

**Issue by makkoli** [freeCodeCamp/league-for-good#39]
On the roster view under the teams tab in the league dashboard, the update column needs to be removed from the array that is used to render the columns. We no longer want to update players through the teams.

**Comment by ajGingrich** [comment]
i'll work on this

**Comment by makkoli** [comment]
Sounds good, thanks.

**Comment by ajGingrich** [comment]
I get two errors when running npm test before making any modifications
 
    ...league-for-good\client\src\components\dashboard\helper\tableTemplate\__original              Table.jsx
    98:24  error  'onSort' is missing in props validation           react/prop-types
    100:32  error  'sortColumnIndex' is missing in props validation  react/prop-types

**Comment by makkoli** [comment]
I have an unmodified master branch and I can't duplicate this when I run the tests. I looked at the file and it seems that if you add this:

```
Headers.propTypes = {
	headers: PropTypes.arrayOf(PropTypes.object),
	onSort: PropTypes.func,
	sortDirection: PropTypes.string,
	sortColumnIndex: PropTypes.number
};
```

to the prop types of the Headers component, I think it will fix it.
I added it and pushed it to the master branch, you can pull it and see if it will fix it.

**Comment by ajGingrich** [comment]
ok great thanks that worked, I just had to switch these two lines because of alphabetical order

    sortDirection: PropTypes.string,
    sortColumnIndex: PropTypes.number
