### ISSUE TITLE
Fix/Edit player form label misaligned

### ISSUE THREAD

**Issue by makkoli** [freeCodeCamp/league-for-good#41]
The "Team" field label in the edit player form under the player tab in the league dashboard is aligned center and needs to be aligned left. 

This issue also affects the add player form under the players tab as well.

There is a player form template that will have to be changed. Any style added for select inputs should be in the style sheet under "client/src/components/style.js"

**Comment by satyadeeproat** [comment]
Hi @makkoli I want to try this one. This one will be my first contribution . Should I make a PR?

**Comment by makkoli** [comment]
Hey @satyadeeproat, you will want to fork the repo and make your changes. Once you got the issue fixed, do npm run test in the root directory and make sure you're passing all the tests. If you do, make a PR and me or @ahstein3521 will review it. We'll either accept it or give feedback on what to fix before we can accept it.

There is also a contributing.md file in the repo you can read your get more information on contributing.

**Comment by satyadeeproat** [comment]
I have made the pull request. You can check it
