### ISSUE TITLE
Feat/View player needs to be styled

### ISSUE THREAD

**Issue by makkoli** [freeCodeCamp/league-for-good#42]
The view player page under the players tab in the league dashboard needs to be styled. There is currently no styling added to this page. As of right now, all styling is being placed in "client/src/components/style.js"

**Comment by satyadeeproat** [comment]
So currently it's just showing ...loading , so we need to display the details of the player here?

**Comment by makkoli** [comment]
It's supposed to display the players information when you click on a player. I'm not sure why you're only getting loading text. When it does load though, it shows the details but it's not formatted at all. It needs to be styled with some css.

**Comment by satyadeeproat** [comment]
@makkoli I am working on the style. I was facing the issue because I just filled the name, last name and email id while adding the data. In that case while viewing that player, you will get the player as undefined and hence it was showing loading

**Comment by makkoli** [comment]
Ah, I see. If you get a chance, could you have it load some default text, if the data is undefined?
