### ISSUE TITLE
Fix/Change description for active teams in a season

### ISSUE THREAD

**Issue by makkoli** [freeCodeCamp/league-for-good#46]
The teams page under the seasons tab in the league dashboard needs to have the title needs to be changed from
Available Teams -> Seasons Active Teams

**Comment by vikramnr** [comment]
@makkoli Let me know https://github.com/vikramnr/league-for-good/commit/343e8bfff7f29a232e10ed6173f51b223ddfe971 if this fixed the issue

**Comment by makkoli** [comment]
@vikramnr That fixed it. You should submit a pull request and reference this issue in your description. Let me know if you need any help on how to do that.

**Comment by vikramnr** [comment]
Yeah will raise it. Thanks

On 12 Aug 2017 11:54 p.m., "makkoli" <notifications@github.com> wrote:
>
> @vikramnr That fixed it. You should submit a pull request and reference
this issue in your description. Let me know if you need any help on how to
do that.
