### ISSUE TITLE
Fix/Remove delete league from settings tab

### ISSUE THREAD

**Issue by makkoli** [freeCodeCamp/league-for-good#48]
The delete league link under the settings tab in the league dashboard needs to be removed.

**Comment by vikramnr** [comment]
@makkoli   I'm fairly new contributing so let me know if I can work on this.

**Comment by makkoli** [comment]
@vikramnr Feel free to work on this and don't be afraid to ask for help if you need it.

**Comment by vikramnr** [comment]
@makkoli  👍

**Comment by vikramnr** [comment]
@makkoli   Should I also remove the [form](https://github.com/freeCodeCamp/league-for-good/tree/3aa213664958d2534090d106c62769ff98e62cc7/client/src/components/dashboard/settings/forms) for delete league?

**Comment by makkoli** [comment]
Yeah, we won't be needing that anymore.

**Comment by paulywill** [comment]
@makkoli May I ask why the ability to remove a league was taken away?

**Comment by makkoli** [comment]
FCC decided they didn't want to have that option available. They didn't want admins to delete leagues and lose all the data associated with them.

**Comment by paulywill** [comment]
@makkoli: That makes sense.  Is there still a need for admins to send a housekeeping request?

FCC could keep the data but create a new record cloning the same data with the changes.

ie "Click here to request League Rename"
    "Click here to request Remove League Listing"
