### ISSUE TITLE
Fix/Break up CSS file

### ISSUE THREAD

**Issue by makkoli** [freeCodeCamp/league-for-good#49]
The CSS file in the "client/src/components/style.js" needs to be broken up into smaller files.

These smaller files and themes.js can be placed in their own directory and referenced using a file that exports all the modules. These will make the css easier to maintain.

**Comment by vikramnr** [comment]
@makkoli  So each theme should be broken up and each will added using `import` statement

**Comment by makkoli** [comment]
Yeah, it's quite a bit tedious to fix this, but you can do it one of two ways. Separate all the style objects into their own files and update the import statements in the components. Or, move all the objects into their own files, import it into an index file and export an object to the components. Then, update the import statements in the components.

This is off the top of my head, there may be a better way to do this.

**Comment by Renestl** [comment]
Is anyone working on this? I will be glad to take a crack at this otherwise.

**Comment by makkoli** [comment]
I don't think anyone is working on this so go for it.
