### ISSUE TITLE
Login is not detecting existing user and does not load users league

### ISSUE THREAD

**Issue by lanesawyer** [freeCodeCamp/league-for-good#5]
I'm getting this error in the console when I log in to the app:

```
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): WriteError({"code":11000,"index":0,"errmsg":"E11000 duplicate key error collection: league-for-good.users inde
x: email_1 dup key: { : \"lanesawyer@gmail.com\" }","op":{"name":"Lane Sawyer","avatar":"https://lh5.googleusercontent.com/-U6Re7TML-ZA/AAAAAAAAAAI/AAAAAAAASu4/yfVVvz0Zxp0/photo.jpg?sz=50","email":"lanes
awyer@gmail.com","_id":"5946074fb9c1181d18e9de4f","__v":0}})
```

It still signs me and loads the app, but none of my existing leagues are shown.

**Comment by makkoli** [comment]
So I ran into this issue again after this PR when I tried to run the app. I found the problem was googleId was not matching the field in the mongoose model which was google_id. Reverting both googleId to google_id solved it.

**Comment by ahstein3521** [comment]
Sorry about that, I thought I had changed it in both files from camelCase
to using the underscore (for consistent field names within the schema).  I
won't let you guys down again
