### ISSUE TITLE
Unexpected token ...

### ISSUE THREAD

**Issue by ajGingrich** [freeCodeCamp/league-for-good#51]
I would like to contribute to this project but when using `npm run dev` I am thrown an error. 

`league-for-good\server\api\registration.js:25
        const player = ({...req.body, ...{ leagueId }});`

From what I understand `...` is ES7 and/or experimental and Babel may not catching it. How should I proceed?

**Comment by ahstein3521** [comment]
That's a syntax error, I will update the master branch later today. In the
meantime, if you want to work on a different branch, just change that line
to :
*const player = Object.assign({}, req.body, { leagueId });*

**Comment by ajGingrich** [comment]
ok thanks!
