### ISSUE TITLE
Issue on setting up Google API credentials

### ISSUE THREAD

**Issue by satyadeeproat** [freeCodeCamp/league-for-good#54]
I have set my .env file like this
MONGO_URI = 'mongodb://localhost:27017/league-for-good'
GOOGLE_CLIENT_ID =  '932757790180-0ref2odnm0v9uemj93ib6n3mhr2hescn.apps.googleusercontent.com'
GOOGLE_CLIENT_SECRET =  'Gh4wqdrg1bnUfYHa2BsnXx3x'
SESSION_SECRET =  'xyz'
GOOGLE_CALLBACK_URL = 'http://localhost:4000/auth/google/callback'

still I am getting this error on choosing the account for login after clicking on login button at localhost:4000
![screen shot 2017-08-17 at 2 57 07 am](https://user-images.githubusercontent.com/10433604/29386175-501ffb44-82f8-11e7-9f7a-1e2beaeeb584.png)

**Comment by DusanSacha** [comment]
Hi, I also set it up recently, tested it right now and it is working for me.

Have you set up OAuth 2.0 client IDs in [Google Dev.console](https://console.developers.google.com) correctly?

Authorized JavaScript origins: http://localhost:4000
Authorized redirect URIs: http://localhost:4000/auth/google/callback

**Comment by satyadeeproat** [comment]
Am I doing it right?
![screen shot 2017-08-17 at 4 11 47 pm](https://user-images.githubusercontent.com/10433604/29408713-e3eeab4a-8366-11e7-8444-066ab4256642.png)

**Comment by DusanSacha** [comment]
I think, you are doing it right. It same on my settings.

Make sure your Google+ API is enabled - in your project Dashboard.
If not enable it under the link on top.

![league](https://user-images.githubusercontent.com/16412025/29409871-7023c910-834e-11e7-971a-6e0f569bd37d.png)

**Comment by satyadeeproat** [comment]
YEs that was the issue . Thanks @DusanSacha

**Comment by ahstein3521** [comment]
Just an FYI for future reference, but you never want to publish sensitive
information like API keys for people to be able  to see. That's why it's
placed in a .env file. I would have google reassign you a new client_id and
client_secret, and use those for your project instance as soon as possible.

**Comment by satyadeeproat** [comment]
yes I have reset that. Thank you for the information

**Comment by paulywill** [comment]
I'm getting stuck on the sign-in waiting for localhost.

any suggestions?

**Comment by paulywill** [comment]
Error
    at Strategy.OAuth2Strategy.parseErrorResponse (/Users/paulgamble/Coding/fcc/league-for-good/node_modules/passport-oauth2/lib/strategy.js:329:12)
    at Strategy.OAuth2Strategy._createOAuthError (/Users/paulgamble/Coding/fcc/league-for-good/node_modules/passport-oauth2/lib/strategy.js:376:16)
    at /Users/paulgamble/Coding/fcc/league-for-good/node_modules/passport-oauth2/lib/strategy.js:166:45
    at /Users/paulgamble/Coding/fcc/league-for-good/node_modules/oauth/lib/oauth2.js:191:18
    at passBackControl (/Users/paulgamble/Coding/fcc/league-for-good/node_modules/oauth/lib/oauth2.js:132:9)
    at IncomingMessage.<anonymous> (/Users/paulgamble/Coding/fcc/league-for-good/node_modules/oauth/lib/oauth2.js:157:7)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
