### ISSUE TITLE
Setup Issue: Error after running "npm run dev"

### ISSUE THREAD

**Issue by Jlevyd15** [freeCodeCamp/league-for-good#60]
I've cloned a copy of the project ran npm install and setup the Google sign in stuff. (created the .env file) after running 'npm run dev' I'm getting an error in registration.js. "Unexpected token ..." 

Looks like node is not able to recognize the spread operator??? Is anyone else seeing this? Any Ideas?

<img width="755" alt="screen shot 2017-08-29 at 8 45 20 pm" src="https://user-images.githubusercontent.com/2600393/29854613-deb4dc1e-8cfb-11e7-8278-eb322cebe529.png">

mongo driver is running @ mongodb://localhost:27017/league-for-good
mongo -version = 3.2.8
node --version = v6.11.1

**Comment by ahstein3521** [comment]
I just pushed a quick fix,. Sorry about that... Let me know if it still isn't working, or if you come across any other issues.

**Comment by Jlevyd15** [comment]
Yup, that was it. Everything seems to be working now, thanks! 👍
