### ISSUE TITLE
Unable to rename or delete league

### ISSUE THREAD

**Issue by paulywill** [freeCodeCamp/league-for-good#64]
The delete link for the league is not working.

![image](https://user-images.githubusercontent.com/602422/31137703-02349ee6-a83a-11e7-98b8-e099e6e5c66a.png)

I accidentally put a team name (ie Eagles) in the league entry.  Unable to rename or delete the league.

**Comment by makkoli** [comment]
@paulywill The delete league feature is to delete the entire league. You may want to do another fork from the repo if you have an old version. That feature has been removed. You can delete a league manually in your mongo database.

**Comment by paulywill** [comment]
@makkoli explained in issue  https://github.com/freeCodeCamp/league-for-good/issues/48

I understand that FCC wants to maintain data on the backend.

I do propose offering a feature to send a "request for rename or delete" which would ideally clone a league record to another record with the rename changes and to remove the league from the user's/admin's listing for a delete respectively.

**Comment by makkoli** [comment]
The rename feature should just change the name in the database and be done by the owner or admin. I opened issue #68 for this feature.
